# ref. https://goreleaser.com/customization/build/
builds:
  - id: quark-cli
    main: ./cmd/quarkcli
    binary: quark-cli
    flags:
      - -v
    # TODO: remove this once we support 32-bit in avalanchego
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: freebsd
        goarch: 386
  - id: quarkvm
    main: ./cmd/quarkvm
    binary: quarkvm
    flags:
      - -v
    # TODO: remove this once we support 32-bit in avalanchego
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: freebsd
        goarch: 386

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: gyuho
    name: quarkvm
